# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog Template
url: http://stopit.github.io
feed: /atom.xml
author_info: <a href="http://stopit.github.io/">yanmeng</a>

myblog:
  gavatar: images/2.jpg
  gpname: alfred
  linkedin: http://www.linkedin.com/in/stopit
  github: https://github.com/stopit
  email: stopit@yeah.net
  coverimgs: []
  postbgimg: []

categories: [python, books]
